project_id = "vvbdmjjovzcfmfqywoty"

[functions.send-application]
verify_jwt = false

[functions.send-invite]
verify_jwt = true

[functions.send-driver-invite]
verify_jwt = true

[functions.track-invite-open]
verify_jwt = false

[functions.get-vehicle-stats]
verify_jwt = true

[functions.sync-vehicles-samsara]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = false

[functions.fetch-carrier-data]
verify_jwt = false

[functions.sync-carriers-fmcsa]
verify_jwt = true

[functions.samsara-webhook]
verify_jwt = false
